# Use the Node.js base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire client application code to the working directory
COPY . .

# Set the command to start the client application
CMD [ "node", "index.js" ]
