name: Build and Push Docker Image - Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_TOOBA }}
          password: ${{ secrets.DOCKER_PASSWORD_TOOBA }}
      - name: Build Docker image
        run: docker build -t tooba29/client:latest ./client
      - name: Push Docker image to Docker Hub
        run: docker push tooba29/client:latest
