name: Build and Push Docker Image - Server
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME_TOOBA }}
           password: ${{ secrets.DOCKER_PASSWORD_TOOBA }}
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Build and push Docker image
         uses: docker/build-push-action@v4
         with:
          context: .
          push: true
          tags: tooba29/docker-img-server:latest
          build-args: |
            MONGO_URL=${{ secrets.ENS_VARS.MONGO_URL }}
            JWT_SECRET=${{ secrets.ENS_VARS.JWT_SECRET }}
            PORT=${{ secrets.ENS_VARS.PORT }}
